# this is the first file fish loading 


# fish_config theme choose "Dracula Official"

if status is-interactive
#    neofetch # Commands to run in interactive sessions can go here
  starship init fish | source
end

neofetch
# set PATH ~/.local/bin:{$PATH}
# set PATH ~/.cargo/bin:{$PATH}
#set PATH ~/.local/share/JetBrains/WebStorm-213.5744.224/bin:{$PATH}
# fish can generate autocompletions from man pages. Completions are written to ~/.local/share/fish/generated_completions/ and can be generated by calling:

# set PATH ~/.local/share/JetBrains/WebStorm-213.7172.31/bin:{$PATH}
# exec fish_update_completions
# fish_add_path ~/.local/bin $PATH
fish_add_path ~/.cargo/bin $PATH
# fish_add_path ~/.local/share/JetBrains/WebStorm-213.7172.31/bin $PATH
# You can also define your own completions in ~/.config/fish/completions/
#Colorscheme: Lava
 set -U fish_color_normal normal
 set -U fish_color_command FF9400
 set -U fish_color_quote BF9C30
 set -U fish_color_redirection BF5B30
 set -U fish_color_end FF4C00
 set -U fish_color_error FFDD73
 set -U fish_color_param FFC000
 set -U fish_color_comment A63100
 set -U fish_color_match --background=brblue
 set -U fish_color_selection white --bold --background=brblack
 set -U fish_color_search_match bryellow --background=brblack
 set -U fish_color_history_current --bold
 set -U fish_color_operator 00a6b2
 set -U fish_color_escape 00a6b2
 set -U fish_color_cwd green
 set -U fish_color_cwd_root red
 set -U fish_color_valid_path --underline
 set -U fish_color_autosuggestion FFC473
 set -U fish_color_user brgreen
 set -U fish_color_host normal
 set -U fish_color_cancel --reverse
 set -U fish_pager_color_prefix normal --bold --underline
 set -U fish_pager_color_progress brwhite --background=cyan
 set -U fish_pager_color_completion normal
 set -U fish_pager_color_description B3A06D
 set -U fish_pager_color_selected_background --background=brblack
 set -U fish_color_option 
 set -U fish_pager_color_selected_completion 
 set -U fish_pager_color_secondary_description 
 set -U fish_pager_color_background 
 set -U fish_color_host_remote 
 set -U fish_pager_color_selected_prefix 
 set -U fish_pager_color_secondary_completion 
 set -U fish_pager_color_secondary_background 
 set -U fish_color_keyword 
 set -U fish_pager_color_selected_description 
 set -U fish_pager_color_secondary_prefix 
